#!/bin/sh
# PBRCloud Update Script for OpenWrt
# Version: 0.1.3 - Persistent rollback, BusyBox compatible, with DRY_RUN support

# Configuration
CONF_FILE="/etc/config/pbrcloud"
DATA_DIR="/etc/pbrcloud"
TMP_DIR="/tmp/pbrcloud-update"
LEARNING_LOG="/tmp/pbrcloud-unknown.log"
DNSMASQ_DIR="/etc/dnsmasq.d"
DNSMASQ_CONF_TARGET="${DNSMASQ_DIR}/pbrcloud-direct.conf"
PBR_SET="pbr_wan_4_dst_ip_user"
UPSTREAM_DNS="119.29.29.29"
MAX_FILE_SIZE_KB=300
BACKUP_CONF="${DATA_DIR}/last-good.conf"

# Default BASE_URL pointing to the gonav8/pbrcloud repository
BASE_URL="https://raw.githubusercontent.com/gonav8/pbrcloud/master/data/compiled"
DIRECT_FILE="direct-domains.txt"
SHA_FILE="sha256sums.txt"

# DRY_RUN mode: 1 to enable, 0 to disable
DRY_RUN="${DRY_RUN:-0}"

log() {
    echo "$(date "+%Y-%m-%d %H:%M:%S") PBRCloud: $1" >> "${TMP_DIR}/pbrcloud-update.log"
    [ "$DRY_RUN" -eq 1 ] && echo "DRY_RUN: $1"
}

error_exit() {
    log "ERROR: $1"
    echo "ERROR: $1" >&2
    rm -rf "$TMP_DIR"
    exit 1
}

# Domain validation function (BusyBox compatible)
validate_domain() {
    domain="$1"
    [ -z "$domain" ] && return 1
    case "$domain" in \#*) return 0 ;; esac
    echo "$domain" | grep -qE "^[a-zA-Z0-9.-]+$" || return 1
    echo "$domain" | grep -qE "\." || return 1
    echo "$domain" | grep -qE "(^-|-$|^\.|\.$)" && return 1
    echo "$domain" | grep -qE "(--|\.\.)" && return 1
    echo "$domain" | grep -qE "\*" && return 1
    return 0
}

# --- Main Script Start ---

# Create temporary directory and log file
mkdir -p "$TMP_DIR" || error_exit "Failed to create temporary directory $TMP_DIR"
log "Starting PBRCloud update..."
[ "$DRY_RUN" -eq 1 ] && echo "--- DRY RUN MODE ENABLED ---"

# Check for uclient-fetch or wget
if command -v uclient-fetch >/dev/null; then
    FETCH_CMD="uclient-fetch -q -O"
elif command -v wget >/dev/null; then
    FETCH_CMD="wget -q -O"
else
    error_exit "Neither uclient-fetch nor wget found. Please install one."
fi

# Download checksums
log "Downloading checksums from ${BASE_URL}/${SHA_FILE}"
${FETCH_CMD} "${TMP_DIR}/${SHA_FILE}" "${BASE_URL}/${SHA_FILE}" || error_exit "Failed to download ${SHA_FILE}"

# Download direct domains list
log "Downloading direct domains list from ${BASE_URL}/${DIRECT_FILE}"
${FETCH_CMD} "${TMP_DIR}/${DIRECT_FILE}" "${BASE_URL}/${DIRECT_FILE}" || error_exit "Failed to download ${DIRECT_FILE}"

# Check file size
FILE_SIZE_BYTES=$(wc -c < "${TMP_DIR}/${DIRECT_FILE}")
FILE_SIZE_KB=$((FILE_SIZE_BYTES / 1024))
if [ "$FILE_SIZE_KB" -gt "$MAX_FILE_SIZE_KB" ]; then
    error_exit "Downloaded file ${DIRECT_FILE} (${FILE_SIZE_KB}KB) exceeds maximum allowed size (${MAX_FILE_SIZE_KB}KB)."
fi

# Validate checksum
log "Validating checksums..."
EXPECTED_HASH=$(grep "${DIRECT_FILE}" "${TMP_DIR}/${SHA_FILE}" | awk '{print $1}')
if [ -z "$EXPECTED_HASH" ]; then
    error_exit "Checksum for ${DIRECT_FILE} not found in ${SHA_FILE}."
fi
ACTUAL_HASH=$(sha256sum "${TMP_DIR}/${DIRECT_FILE}" | awk '{print $1}')

if [ "$EXPECTED_HASH" != "$ACTUAL_HASH" ]; then
    error_exit "Checksum mismatch for ${DIRECT_FILE}. Expected: ${EXPECTED_HASH}, Actual: ${ACTUAL_HASH}"
fi
log "Checksum validation successful."

# Generate dnsmasq config to a temporary file
log "Generating new dnsmasq configuration..."
NEW_DNSMASQ_CONF_TMP="${TMP_DIR}/pbrcloud-direct.conf.new"
cat <<EOF > "${NEW_DNSMASQ_CONF_TMP}"
# Generated by PBRCloud - DO NOT EDIT
# Last updated: $(date "+%Y-%m-%d %H:%M:%S")
EOF

INVALID_DOMAINS=0
while IFS= read -r domain || [ -n "$domain" ]; do
    [ -z "$domain" ] && continue
    case "$domain" in \#*) continue ;; esac

    if validate_domain "$domain"; then
        echo "server=/$domain/$UPSTREAM_DNS" >> "${NEW_DNSMASQ_CONF_TMP}"
        echo "nftset=/$domain/4#inet#fw4#$PBR_SET" >> "${NEW_DNSMASQ_CONF_TMP}"
    else
        log "Skipping invalid domain: $domain"
        # Initial learning support: invalid downloaded domains are logged
        echo "$domain" >> "$LEARNING_LOG"
        INVALID_DOMAINS=$((INVALID_DOMAINS + 1))
    fi
done < "${TMP_DIR}/${DIRECT_FILE}"

if [ "$INVALID_DOMAINS" -gt 0 ]; then
    log "Warning: Encountered ${INVALID_DOMAINS} invalid domains in the list."
fi

# Compare with existing config
if [ -f "$DNSMASQ_CONF_TARGET" ]; then
    if command -v diff >/dev/null; then
        if diff -q "${NEW_DNSMASQ_CONF_TMP}" "${DNSMASQ_CONF_TARGET}" >/dev/null 2>&1; then
            log "No changes detected. Exiting."
            rm -rf "$TMP_DIR"
            exit 0
        fi
    else
        OLD_CONTENT=$(cat "${DNSMASQ_CONF_TARGET}")
        NEW_CONTENT=$(cat "${NEW_DNSMASQ_CONF_TMP}")
        if [ "$OLD_CONTENT" = "$NEW_CONTENT" ]; then
            log "No changes detected. Exiting."
            rm -rf "$TMP_DIR"
            exit 0
        fi
    fi
fi

if [ "$DRY_RUN" -eq 1 ]; then
    log "Dry run: Generated configuration saved at ${NEW_DNSMASQ_CONF_TMP}"
    echo "--- Generated Configuration (First 10 lines) ---"
    head -n 10 "${NEW_DNSMASQ_CONF_TMP}"
    echo "--- End of Preview ---"
    log "Dry run: Skipping installation and service restart."
    exit 0
fi

log "Changes detected. Applying new configuration..."

# Create persistent data directory if it doesn't exist
mkdir -p "$DATA_DIR"

# Backup current config to persistent storage
if [ -f "$DNSMASQ_CONF_TARGET" ]; then
    log "Backing up current config to ${BACKUP_CONF}"
    cp "${DNSMASQ_CONF_TARGET}" "${BACKUP_CONF}" || log "Warning: Failed to backup current config."
fi

# Atomically install new config
mv "${NEW_DNSMASQ_CONF_TMP}" "${DNSMASQ_CONF_TARGET}" || error_exit "Failed to install new config."

# Restart services
log "Restarting services..."
RESTART_FAILED=0
/etc/init.d/dnsmasq restart || RESTART_FAILED=1

if [ -x "/etc/init.d/pbr" ]; then
    if /etc/init.d/pbr enabled; then
        /etc/init.d/pbr restart || RESTART_FAILED=1
    else
        log "PBR service not enabled. Skipping."
    fi
fi

if [ "$RESTART_FAILED" -eq 1 ]; then
    log "ERROR: Restart failed. Restoring persistent backup."
    if [ -f "${BACKUP_CONF}" ]; then
        cp "${BACKUP_CONF}" "${DNSMASQ_CONF_TARGET}"
        /etc/init.d/dnsmasq restart
        error_exit "Restored persistent backup due to failure."
    else
        error_exit "Restart failed and no backup found."
    fi
else
    log "Update completed successfully."
fi

rm -rf "$TMP_DIR"
log "PBRCloud update finished."
